### ISSUE TITLE
Selecting -1 party crash

### ISSUE THREAD

**Issue by danorris709** [Daniel-Forge-Development/Simple-STS#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SingleUseAltar (SingleUseAltar-1.12.2-1.0.0.jar)
  SpongeCoremod (spongeforge-1.12.2-2838-7.4.7.jar)
  DrowpzeeCoreLoadingPlugin (Drowpzee-3.0.4.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  PCCore (AdminPC-0.5d.jar)
  MixinsCoreMod (DisableTrainerCard-Mixin.jar)
  PixelmoneyCoreMod (PixelMoney-1.12.2-3.0.6-server.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/6/22 3:23 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -1
	at com.envyful.simple.sts.forge.ui.STSPartyUI.lambda$null$0(STSPartyUI.java:87)
	at com.envyful.simple.sts.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_414_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.envyful.simple.sts.forge.ui.STSPartyUI.lambda$null$0(STSPartyUI.java:87)
	at com.envyful.simple.sts.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_414_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zjk000$onCrashReport(MinecraftServer.java:4687)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:750)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-99-generic
	Java Version: 1.8.0_322, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 2270201688 bytes (2165 MB) / 5175730176 bytes (4935 MB) up to 10719985664 bytes (10223 MB)
	JVM Flags: 11 total; -Xms128M -Xmx10240M -XX:-OmitStackTraceInFastThrow -XX:+AggressiveOpts -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+CMSIncrementalMode
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 161 mods loaded, 161 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State  | ID                  | Version                | Source                                         | Signature                                |
	|:------ |:------------------- |:---------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                 | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42                   | minecraft.jar                                  | None                                     |
	| LCHIJA | sampler             | 1.84                   | sampler-1.84.jar                               | None                                     |
	| LCHIJA | FML                 | 8.0.99.99              | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860           | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | spongeapi           | 7.4.0-5ea6215          | spongeforge-1.12.2-2838-7.4.7.jar              | None                                     |
	| LCHIJA | sponge              | 1.12.2-7.4.7           | spongeforge-1.12.2-2838-7.4.7.jar              | None                                     |
	| LCHIJA | spongeforge         | 1.12.2-2838-7.4.7      | spongeforge-1.12.2-2838-7.4.7.jar              | None                                     |
	| LCHIJA | atlantis            | 4.2.2                  | Atlantis-1.12.2-4.2.2-beta.jar                 | None                                     |
	| LCHIJA | pixelmon            | 8.3.6                  | Pixelmon-1.12.2-8.3.6-server.jar               | None                                     |
	| LCHIJA | adminpc             | 0.5                    | AdminPC-0.5d.jar                               | None                                     |
	| LCHIJA | animalgenocide      | 1.0.0                  | AnimalGenocide-1.0-SNAPSHOT.jar                | None                                     |
	| LCHIJA | anotherpokestop     | @VERSION@              | AnotherPokeStop-1.12.2-2.4.1.jar               | None                                     |
	| LCHIJA | gts                 | 1.12.2-7.1.2-universal | AquaGTS-1.12.2-7.1.2-universal.jar             | None                                     |
	| LCHIJA | aquaplaytime        | 1.12.2-1.1.0-universal | AquaPlaytime-1.12.2-1.1.0-universal.jar        | None                                     |
	| LCHIJA | aquashards          | 1.12.2-1.2.2-universal | AquaShards-1.12.2-1.2.2-universal.jar          | None                                     |
	| LCHIJA | betterbeastspawner  | 1.1.2                  | BetterBeastSpawner-1.1.2.jar                   | None                                     |
	| LCHIJA | libcious            | 1.5.10                 | Libcious-1.5.10.jar                            | None                                     |
	| LCHIJA | breakablepokeloot   | 1.0.0                  | BreakablePokeloot-1.0.jar                      | None                                     |
	| LCHIJA | buymove             | 2.1                    | buymove-2.1.jar                                | None                                     |
	| LCHIJA | cable-libs          | 1.2.0                  | cable-libs-1.2.0.jar                           | None                                     |
	| LCHIJA | catchinfo           | 1.0.0-SNAPSHOT         | CatchInfo-1.12.2-1.0.1-SNAPSHOT.jar            | None                                     |
	| LCHIJA | craftgone           | 1.0                    | CraftGone-1.0.jar                              | None                                     |
	| LCHIJA | cranegame           | 1.2.0                  | CraneGame-1.2.0.jar                            | None                                     |
	| LCHIJA | cursethebindings    | 1.0                    | CurseTheBindings-1.0-SNAPSHOT.jar              | None                                     |
	| LCHIJA | dailies             | 1.12.2-2.3.1-universal | Dailies-1.12.2-2.3.1-universal.jar             | None                                     |
	| LCHIJA | drowpzee            | 3.0.4                  | Drowpzee-3.0.4.jar                             | None                                     |
	| LCHIJA | eggnotifierplus     | 1.0.0                  | EggNotifierPlus-1.0-SNAPSHOT.jar               | None                                     |
	| LCHIJA | endshops            | 0.9                    | EndShops-0.9-NOSPONGE.jar                      | None                                     |
	| LCHIJA | envyantilag         | 1.0.2                  | EnvyAntiLag-Forge-1.0.2-1.12.2.jar             | None                                     |
	| LCHIJA | evolvefix           | 1.2                    | evolvefix-1.2.jar                              | None                                     |
	| LCHIJA | fixot               | 1.0.0                  | FixOT-1.0-SNAPSHOT.jar                         | None                                     |
	| LCHIJA | flashplus           | 1.6.2                  | FlashPlus-1.6.2-shadow.jar                     | None                                     |
	| LCHIJA | flashspec           | 2.8.0                  | FlashSpec-2.8.0.jar                            | None                                     |
	| LCHIJA | forgelin            | 1.8.4                  | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | forgeplaceholderapi | 1.0.0                  | ForgePlaceholderAPI-Forge.jar                  | None                                     |
	| LCHIJA | gooeylibs           | 1.0.6                  | GooeyLibs-1.0.6.jar                            | None                                     |
	| LCHIJA | gooeylibs2          | 2.2.0                  | GooeyLibs-2.2.0.jar                            | None                                     |
	| LCHIJA | invasion            | 2.4.3                  | Invasion-2.4.3.jar                             | None                                     |
	| LCHIJA | itemmodifiers       | 1.0.9                  | ItemModifiers-1.12.2-1.0.9.jar                 | None                                     |
	| LCHIJA | itemshrinefee       | 1.2.2                  | ItemShrineFee-1.2.2.jar                        | None                                     |
	| LCHIJA | killthemall         | 1.12.2-1.0.1-universal | KillThemAll-1.12.2-1.0.1-universal.jar         | None                                     |
	| LCHIJA | leaderboard         | 3.1.0                  | Leaderboard-3.1.0.jar                          | None                                     |
	| LCHIJA | legendaryplus       | 7.0.1                  | LegendaryPlus-7.0.1.jar                        | None                                     |
	| LCHIJA | legendaryspawn      | 1.4                    | LegendarySpawn-1.4.jar                         | None                                     |
	| LCHIJA | legenddefender      | 1.0.5                  | LegendDefender-1.0.5.jar                       | None                                     |
	| LCHIJA | pokekilltype        | 1.0                    | ModBase-1.12.2-1.1.0.jar                       | None                                     |
	| LCHIJA | moveskillcontroller | 1.0.4                  | MoveSkillController-1.12.2-1.0.4-universal.jar | None                                     |
	| LCHIJA | nbtedit             | 1.11.2-2.0.2           | NBTEdit-1.12-2.0.2.jar                         | None                                     |
	| LCHIJA | nerfthis            | 1.7                    | NerfThis-1.7.jar                               | None                                     |
	| LCHIJA | npcextensions       | 2.6.0-BETA             | NPCExtensions-1.12.2-2.6.0-BETA.jar            | None                                     |
	| LCHIJA | npcfiles            | 1.0.1                  | NPCFiles-1.0.1-SNAPSHOT.jar                    | None                                     |
	| LCHIJA | otfix               | 1.0.0                  | OTFix-1.0.0.jar                                | None                                     |
	| LCHIJA | pixelextras         | 2.5.17                 | PixelExtras-1.12.2-2.5.17-universal.jar        | None                                     |
	| LCHIJA | pixelhuntremastered | 2.1.3                  | PixelHuntRemastered-Forge-2.1.3.jar            | None                                     |
	| LCHIJA | pixelmonbroadcasts  | 1.12.2-1.2.3-universal | PixelmonBroadcasts-1.12.2-1.2.3-universal.jar  | None                                     |
	| LCHIJA | pixelmonwikigui     | 1.1.5                  | pixelmonwikigui-1.1.5.jar                      | None                                     |
	| LCHIJA | eoboosters          | 0.5                    | PokeBoosters.jar                               | None                                     |
	| LCHIJA | pokedisplay         | 3.0                    | PokeDisplay-3.0.jar                            | None                                     |
	| LCHIJA | pokelog             | 1.0.6                  | PokeLog-1.0.6.jar                              | None                                     |
	| LCHIJA | pokeraid            | 1.0                    | PokeRaid.jar                                   | None                                     |
	| LCHIJA | pokeshinybuff       | 1.2.7                  | PokeShinyBuff-1.2.7.jar                        | None                                     |
	| LCHIJA | poketop             | 1.1.4                  | poketop-1.0.5-8.3.1_fixed.jar                  | None                                     |
	| LCHIJA | pokeview            | 2.0                    | PokeView-2.0.jar                               | None                                     |
	| LCHIJA | ranchdrops          | 1.1                    | RanchDrops-1.1.jar                             | None                                     |
	| LCHIJA | ranchlimiter        | 1.0.3                  | RanchLimiter-1.4-Fix.jar                       | None                                     |
	| LCHIJA | randomcommands      | 1.0.3                  | RandomCommands-1.0.3-SNAPSHOT.jar              | None                                     |
	| LCHIJA | randomitem          | 1.0.9                  | RandomItem-1.0.9.jar                           | None                                     |
	| LCHIJA | rarehas             | 1.0.1                  | RareHAs-1.0.1-SNAPSHOT.jar                     | None                                     |
	| LCHIJA | ratemodifiers       | 1.0                    | ratemodifiers-2.1-SNAPSHOT.jar                 | None                                     |
	| LCHIJA | reforgedbingo       | 1.0.0                  | ReforgedBingo-Forge-1.0.0.jar                  | None                                     |
	| LCHIJA | retrievablehealer   | 1.0.2                  | RetrievableHealer-1.0.2.jar                    | None                                     |
	| LCHIJA | sharkybuilder       | 1.4.0                  | SharkyBuilder-1.0.jar                          | None                                     |
	| LCHIJA | shulkerbags         | 1.0.3                  | ShulkerBags-1.1.0.jar                          | None                                     |
	| LCHIJA | simplests           | 1.1.2                  | SimpleSTS-Forge-1.1.2.jar                      | None                                     |
	| LCHIJA | spleef              | 1.2.3                  | Spleef-1.2.3.jar                               | None                                     |
	| LCHIJA | supplycrates        | 1.0.6                  | SupplyCrates-1.0.6.jar                         | None                                     |
	| LCHIJA | tapulevel           | 1.5.2                  | TapuLevel-1.5.2.jar                            | None                                     |
	| LCHIJA | texturetokens       | 1.12.2-1.0.0-universal | TextureTokens-1.12.2-1.0.0-universal.jar       | None                                     |
	| LCHIJA | trainercommands     | 2.5.0                  | TrainerCommands-1.12.2-2.5.0-universal.jar     | None                                     |
	| LCHIJA | trainercooldown     | 5.0                    | TrainerCooldown-5.0-shadow.jar                 | None                                     |
	| LCHIJA | traineritem         | 4.1.1                  | TrainerItem-4.1.1-shadow.jar                   | None                                     |
	| LCHIJA | towerbattle         | 2.2.1                  | TrainerPermission-2.2.1-shadow.jar             | None                                     |
	| LCHIJA | unbreed             | 4.0                    | Unbreed-4.0.jar                                | None                                     |
	| LCHIJA | untradeableeggs     | 1.0.0                  | UntradeableEggs-1.0-SNAPSHOT.jar               | None                                     |
	| LCHIJA | wondertrade         | 5.2.4                  | WonderTrade-Forge-5.2.4.jar                    | None                                     |
	| LCHIJA | dropprevent         | 1.1                    | WTFDropprevent-1.1.jar                         | None                                     |
	| LCHIJA | galarorb            | 1.0.0                  | WTFGalarOrb-2.0.jar                            | None                                     |
	| LCHIJA | pixelmonsacrifice   | 1.1                    | WTFPixelmonSacrifice-1.1.jar                   | None                                     |
	| LCHIJA | zombiestone         | 1.0.0                  | WTFZombieStone-2.0.jar                         | None                                     |

	Plugins:

	| State  | ID                         | Version                   | Source                                                        | Signature |
	|:------ |:-------------------------- |:------------------------- |:------------------------------------------------------------- |:--------- |
	| LCHIJA | asdc                       | 1.0                       | AntiShulkerDispenserCrash-1.0.jar                             | None      |
	| LCHIJA | nuvotifier                 | 2.5.3                     | Nuvotifier-2.5.3.jar                                          | None      |
	| LCHIJA | aurionsvotelistener        | 2.4.2                     | AurionVoteListener-2.4.2-S7.1.0.jar                           | None      |
	| LCHIJA | nucleus                    | 1.14.6-S7.1               | Nucleus-1.14.6-S7.1-MC1.12.2-plugin.jar                       | None      |
	| LCHIJA | awayfromspawns             | 1.4                       | AwayFromSpawns-Nucleus.jar                                    | None      |
	| LCHIJA | battleafk                  | 1.2                       | BattleAFK-Nv1-1.2.jar                                         | None      |
	| LCHIJA | catclearlag                | 0.9.0                     | CatClearLag-0.9.5.1.jar                                       | None      |
	| LCHIJA | cmdcontrol                 | 1.2.0                     | CmdControl-s7.1-v1.2.0.jar                                    | None      |
	| LCHIJA | cmdscheduler               | 1.1.1                     | CmdScheduler-s7.1-v1.1.1.jar                                  | None      |
	| LCHIJA | placeholderapi             | 4.4                       | PlaceholderAPI-4.4.jar                                        | None      |
	| LCHIJA | command-utils              | 2.4.0                     | command-utils-2.4.0.jar                                       | None      |
	| LCHIJA | commanditems               | 2.3                       | CommandItems-2.3.jar                                          | None      |
	| LCHIJA | cranegame-sponge           | 1.2.0                     | CraneGame-1.2.0.jar                                           | None      |
	| LCHIJA | dores                      | 1.7.1                     | dOres-1.7.1.jar                                               | None      |
	| LCHIJA | pixelmoneconomybridge      | 2.0.7                     | EcoBridge-1.12.2-2.0.7.jar                                    | None      |
	| LCHIJA | economylite                | 2.15.1                    | EconomyLite-7.1.0-2.15.1.jar                                  | None      |
	| LCHIJA | eventoquiz                 | 1.0.0                     | EventoQuiz.jar                                                | None      |
	| LCHIJA | fastasyncworldedit         | development               | FastAsyncWorldEdit-sponge112-19.11.13-5505943-1282-22.3.5.jar | None      |
	| LCHIJA | worldedit                  |                           | FastAsyncWorldEdit-sponge112-19.11.13-5505943-1282-22.3.5.jar | None      |
	| LCHIJA | luckperms                  | 5.3.98                    | LuckPerms-Sponge-5.3.98.jar                                   | None      |
	| LCHIJA | griefdefender              | 2.1.3                     | griefdefender-sponge-2.1.3.jar                                | None      |
	| LCHIJA | triump-gui                 | 3.1.0                     | griefdefender-sponge-2.1.3.jar                                | None      |
	| LCHIJA | holograms                  | 3.1.5                     | holograms-3.1.5.jar                                           | None      |
	| LCHIJA | huskyui                    | 0.6.0PRE4                 | HuskyUI-v0.6.0-PRE4-API7.jar                                  | None      |
	| LCHIJA | huskycrates                | 2.0.0RC3                  | HuskyCrates.jar                                               | None      |
	| LCHIJA | lookingglass               | 1.0.2                     | LookingGlass-1.0.2.jar                                        | None      |
	| LCHIJA | ultimatechat               | 1.9.1                     | UltimateChat-1.9.1-b281-Universal.jar                         | None      |
	| LCHIJA | magibridge                 | 2.11.1                    | MagiBridge-API7-2.11.1.jar                                    | None      |
	| LCHIJA | mmcreboot                  | 2.3.4                     | MMCReboot-2.3.4-API-7.jar                                     | None      |
	| LCHIJA | mmcrestrict                | 1.7.1                     | MMCRestrict-1.7.1-API-7.jar                                   | None      |
	| LCHIJA | modbanner                  | 1.1.5                     | ModBanner-1.1.5.jar                                           | None      |
	| LCHIJA | multibaltop                | 1.3                       | MultiBalTop-1.3-SNAPSHOT.jar                                  | None      |
	| LCHIJA | multicurrency              | 1.0.1                     | Multicurrency-2.0.1-custom.jar                                | None      |
	| LCHIJA | noportal                   | 1.1.0                     | NoPortal-1.1.0.jar                                            | None      |
	| LCHIJA | pixelautomessages          | 1.0.3                     | PixelAutoMessages-1.0.3-b15.jar                               | None      |
	| LCHIJA | pixelexprates              | 1.0.1                     | PixelExpRates-1.0.1.jar                                       | None      |
	| LCHIJA | pixelmoney                 | 3.0.6                     | PixelMoney-1.12.2-3.0.6-server.jar                            | None      |
	| LCHIJA | pixelmonoverlay            | 1.1.1                     | pixelmonoverlay-1.1.1.jar                                     | None      |
	| LCHIJA | pixelmonplaceholders       | 2.1.9                     | PixelmonPlaceholders-2.1.9.jar                                | None      |
	| LCHIJA | plan                       | 5.4 build 1583            | Plan-5.4-build-1583.jar                                       | None      |
	| LCHIJA | pokedexrewards             | 0.8.2-t2                  | PokedexRewards-0.8.2-t2.jar                                   | None      |
	| LCHIJA | poketeams                  | 4.0.8                     | PokeTeams-4.0.9.jar                                           | None      |
	| LCHIJA | prank                      | 3.0                       | PRank-1.12.2-3.0-S7.3.0-STABLE.jar                            | None      |
	| LCHIJA | projectwebhooks            | 1.0-SNAPSHOT              | ProjectWebhooksSponge-1.0-SNAPSHOT.jar                        | None      |
	| LCHIJA | protocolcontrol            | 0.0.2                     | protocolcontrol-0.0.2.jar                                     | None      |
	| LCHIJA | realmap                    | 1.0                       | RealMap-1.0.jar                                               | None      |
	| LCHIJA | bread                      | 0.3.4                     | RedstoneDetector.jar                                          | None      |
	| LCHIJA | signlogger                 | 1.5                       | SignLogger.jar                                                | None      |
	| LCHIJA | slashdiscord               | 1.4.0                     | SlashDiscord-1.4.0.jar                                        | None      |
	| LCHIJA | spark                      | 1.4.3                     | spark.jar                                                     | None      |
	| LCHIJA | spleef-sponge              | 1.2.3                     | Spleef-1.2.3.jar                                              | None      |
	| LCHIJA | sponge-vip                 | 1.0.0                     | SpongeVIP-1.8.jar                                             | None      |
	| LCHIJA | spotlin                    | 0.2.0                     | spotlin-7.0.0-1.3.11-0.2.0.jar                                | None      |
	| LCHIJA | tabmanager                 | 2.1.3-S7.0-MC1.12.2       | TabManager-2.1.3-S7.0-MC1.12.2.jar                            | None      |
	| LCHIJA | tapuplaceholder            | 1.1                       | TapuPlaceholder-Sponge-1.2.0.jar                              | None      |
	| LCHIJA | titlebroadcaster           | 1.2.0-SNAPSHOT            | TitleBroadcaster-1.0.0-SNAPSHOT-all.jar                       | None      |
	| LCHIJA | tournaments                | 2.7.0                     | Tournaments-1.12.2-2.7.0.jar                                  | None      |
	| LCHIJA | virtualchest               | 1.0.2                     | VirtualChest-1.0.2.jar                                        | None      |
	| LCHIJA | voteparty                  | 1.3.4                     | VoteParty-1.3.4.jar                                           | None      |
	| LCHIJA | welcometitles              | 2.0.0                     | WelcomeTitles-2.0.0.jar                                       | None      |
	| LCHIJA | leventos                   | 1.1.4                     | WTFEventos-Sponge-1.1.4.jar                                   | None      |
	| LCHIJA | night-vision-toggle        | 1.0.0                     | WTFLuz.jar                                                    | None      |
	| LCHIJA | wtfoptimization            | 1.0-SNAPSHOT              | WTFOptimization-1.0-SNAPSHOT.jar                              | None      |
	| LCHIJA | pixelmondrops              | 1.0.0-custom              | WTFPixelmonDrops-3.0.0-custom.jar                             | None      |
	| LCHIJA | whosthatpixelmon           | 1.1.0                     | WTFPokémon-Adivinha-1.1.0-PT-Br.jar                           | None      |
	| LCHIJA | wtfshoplistener            | 1.0                       | WTFShopListener-1.0-sponge.jar                                | None      |
	| LCHIJA | wtfshulkerhopperprevention | 1.0-SNAPSHOT              | WTFShulkerHopperPrevention-1.0-SNAPSHOT.jar                   | None      |
	| LCHIJA | wtfn-tournamentsexpansion  | 1.0-SNAPSHOT              | WTFTournamentsExpansion-3.0-SNAPSHOT.jar                      | None      |
	| LCHIJA | wtftransactions            | 1.3.2                     | WTFTransactions-1.3.2.jar                                     | None      |
	| LCHIJA | yourcustompaintings        | 1.2.0.26-351edc7-SNAPSHOT | yourcustompaintings-1.2.0.26-351edc7-SNAPSHOT.jar             | None      |

	Loaded coremods (and transformers): 
SingleUseAltar (SingleUseAltar-1.12.2-1.0.0.jar)
  shadows.sua.Transformer
SpongeCoremod (spongeforge-1.12.2-2838-7.4.7.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
DrowpzeeCoreLoadingPlugin (Drowpzee-3.0.4.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
PCCore (AdminPC-0.5d.jar)
  tk.endoffile.adminpc.asm.WrapperInjector
ShopsCore (BiShops-2.0.3.jar)
  
MixinsCoreMod (DisableTrainerCard-Mixin.jar)
  
PixelmoneyCoreMod (PixelMoney-1.12.2-3.0.6-server.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 51 / 100; [EntityPlayerMP['BetoBr1557'/778, l='world', x=-13493.32, y=166.88, z=11508.81], EntityPlayerMP['misterio55'/832, l='spawn-oficial', x=398.31, y=93.00, z=244.72], EntityPlayerMP['Clenzin'/841, l='DIM1', x=-18.78, y=65.17, z=-24.83], EntityPlayerMP['Higurashi83'/937, l='world', x=13044.66, y=63.00, z=12090.00], EntityPlayerMP['zVegxis'/1212, l='DIM1', x=-9.29, y=65.00, z=-23.99], EntityPlayerMP['Roboludo'/1252, l='world', x=-5854.07, y=69.00, z=-296.82], EntityPlayerMP['ArceusRZD'/1484, l='world', x=-5420.24, y=155.00, z=9408.06], EntityPlayerMP['Paodebatatata'/1585, l='mina', x=4994.57, y=13.00, z=-249.77], EntityPlayerMP['mitojvpa'/1656, l='world', x=8686.25, y=52.00, z=-7871.06], EntityPlayerMP['SaYuriChan'/1789, l='world', x=-13536.78, y=154.64, z=11518.70], EntityPlayerMP['TheKitsune'/2204, l='DIM1', x=2.42, y=64.00, z=-3.43], EntityPlayerMP['miyuukk'/2577, l='safari', x=-349.30, y=55.00, z=145.75], EntityPlayerMP['Dudu2909'/3923, l='world', x=5715.86, y=73.06, z=-11643.87], EntityPlayerMP['Gnar0713'/4029, l='world', x=2997.46, y=73.00, z=5353.88], EntityPlayerMP['Boiolinha'/4158, l='world', x=-4146.34, y=75.61, z=-8170.87], EntityPlayerMP['Slyther21'/5441, l='safari', x=521.28, y=32.00, z=452.18], EntityPlayerMP['Filho_Do_Patoxd'/6005, l='world', x=-9139.72, y=70.00, z=-5119.38], EntityPlayerMP['caiopvp'/7926, l='spawn-oficial', x=396.48, y=87.00, z=205.55], EntityPlayerMP['rewrer7458'/8192, l='DIM1', x=3.29, y=63.00, z=5.61], EntityPlayerMP['mangueira7'/12564, l='safari', x=-349.51, y=55.00, z=147.98], EntityPlayerMP['hhjdfk'/12524, l='world', x=-5063.17, y=64.00, z=9851.50], EntityPlayerMP['WhoMitsu'/20815, l='world', x=-4919.65, y=64.00, z=-6422.91], EntityPlayerMP['akashizin'/27708, l='world', x=-5378.42, y=156.00, z=9287.11], EntityPlayerMP['lucariotube'/28294, l='world', x=-4995.68, y=65.00, z=-9495.73], EntityPlayerMP['loud_pretim'/29928, l='spawn-oficial', x=761.65, y=39.06, z=219.54], EntityPlayerMP['DarKvecplayer'/30023, l='world', x=4112.35, y=44.00, z=-6529.48], EntityPlayerMP['umrzera'/30567, l='world', x=-6001.40, y=64.06, z=-4699.18], EntityPlayerMP['kauanzinpvp2'/32546, l='world', x=-6683.03, y=83.12, z=1472.08], EntityPlayerMP['pedrohjh'/34509, l='safari', x=524.24, y=35.00, z=434.08], EntityPlayerMP['darkvicenzo'/34522, l='world', x=8688.70, y=55.02, z=-7868.88], EntityPlayerMP['LFNOGUEIRA'/35775, l='safari', x=370.96, y=42.40, z=-22.12], EntityPlayerMP['clayton123'/36546, l='spawn-oficial', x=406.65, y=86.00, z=240.53], EntityPlayerMP['Maxx1'/36576, l='world', x=-5380.17, y=64.06, z=9769.90], EntityPlayerMP['N3ON'/40548, l='world', x=-5190.33, y=73.00, z=-1815.70], EntityPlayerMP['negolettgmes'/45780, l='world', x=18642.63, y=117.15, z=19559.64], EntityPlayerMP['leader'/48042, l='world', x=-2942.50, y=68.00, z=6425.50], EntityPlayerMP['luiz_mine'/49277, l='safari', x=515.08, y=25.00, z=180.31], EntityPlayerMP['Minato_53'/51183, l='world', x=-8257.09, y=95.35, z=4407.16], EntityPlayerMP['carbono12'/51883, l='safari', x=-349.43, y=55.00, z=144.93], EntityPlayerMP['veio'/51954, l='spawn-oficial', x=395.38, y=92.39, z=246.08], EntityPlayerMP['FrostCria'/52000, l='safari', x=-506.13, y=84.00, z=-394.68], EntityPlayerMP['Yukumo1601'/54954, l='DIM1', x=66.58, y=59.00, z=9.02], EntityPlayerMP['HIPNOZE'/57265, l='spawn', x=-787.10, y=102.50, z=-473.77], EntityPlayerMP['Drakenn123'/57532, l='world', x=8684.63, y=52.00, z=-7865.86], EntityPlayerMP['enzikkkj'/57781, l='world', x=2515.52, y=99.80, z=-1001.07], EntityPlayerMP['Beehore'/58635, l='safari', x=-17.36, y=27.74, z=-81.32], EntityPlayerMP['yZephhy'/59220, l='spawn', x=-797.45, y=96.00, z=-470.26], EntityPlayerMP['Luizao171'/61221, l='spawn', x=-796.13, y=96.50, z=-473.01], EntityPlayerMP['Kamikiz'/61552, l='world', x=2485.55, y=83.25, z=-751.18], EntityPlayerMP['espiao87'/61557, l='spawn-oficial', x=391.00, y=88.00, z=210.00], EntityPlayerMP['bife'/62423, l='world', x=-2957.05, y=81.00, z=12171.59]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by danorris709** [comment]
Fixed in next version
